#!/usr/bin/python3
# password-hashing.py

import hashlib
print("Password Hashing Program")
print("------------------------")
print()

# Obtain password input from the user
password = input("Enter a password to hash: ")

# Hash the password using Sha-256
sha256 = hashlib.sha256()
sha256.update(password.encode('utf-8'))
hashed_password = sha256.hexdigest()

# Print the hashed password
print("\nThe SHA-256 hash of the password is: {}".format(hashed_password))
